### PR TITLE
Types

### PR DESCRIPTION
**Pull request by tbo47**

### CODE REVIEW

**Comment by tbo47** [comment]
It would be nice to have the `types` in the published package in npmjs. For developers using typescript instead of javascript.

In this pull-request I only migrate `src/diagram/diagram.js` to a syntax that `typescript` understands. 

Let me know if you like this approach.

**Comment by tbo47** [comment]
or maybe just switching to typescript instead of javascript?

**Comment by AlexeyBoiko** [comment]
Thanks for suggest.  
<br />
> It would be nice to have the types in the published package in npmjs.

Agree. I have to add `types` to npm package.

Public diagram interface is here:
https://github.com/AlexeyBoiko/DgrmJS/blob/main/src/diagram/diagram-public-types.ts
Types in `diagram-public-types.ts` must be the only types developer need to use DgrmJS.

The problem:
`diagram-public-types.ts` depends on some types from presenter layer. It is needed to remove this dependence.
Then I'll add `diagram-public-types.ts` to npm package.
<br />
> For developers using typescript instead of javascript

Not only TypeScript developers use `types`. JavaScript developers olso use `types`. `Types` is used for creating DgrmJs.

TypeScript notations can be used along with JSDoc.
https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html
<br />
> switching to typescript instead of javascript?

JavaScript with JSDoc and TypeScript notations give the developer the same tooling:
- type checking
- intellisense
- find all references
- renaming
- checking that the object implements the interface

I don't see why to use TypeScript.
Pros of not using the TypeScript compiler:
- JS code is exactly what you wrote,
- speeds up development — no need to wait for compilation,
- no need for map files, easier to debug.
- easier build process

[Blog post with more information](https://medium.com/codex/javascript-svg-diagram-editor-which-weighs-6-5-less-than-bootstrap-open-source-library-b753feaaf835)

**Comment by AlexeyBoiko** [comment]
Now all public types in `diagram-public-types.ts`.

You can build DgrmJS library to single js-file:
`npm run build-dgrm-npm`

Singls js file will be in folder
`\dist\diagram-npm-package`

Include this file to your typescript app. And use types from `diagram-public-types.ts`.

**Pull request closed without merging**
